### GET SONGS
GET http://localhost:8383/songs


### GET USERS
GET http://localhost:8383/users


### GET FRIEND
GET http://localhost:8383/friends/james


### ADD A FRIEND
POST http://localhost:8383/addSong
Content-Type: application/json

{
    "bpm": 80,
    "bpms": [
        80,
        90,
        100,
        110
    ],
    "description": "Basic Rhythm",
    "gender": "basic",
    "id": "",
    "date_creation":"",
    "isNew": true,
    "name": "Basic Rhythm 1",
    "url": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%201.mp3?alt=media&token=f5ab189d-51c1-4f6b-be29-044e08d630b0",
    "urls": {
        "80": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%201.mp3?alt=media&token=f5ab189d-51c1-4f6b-be29-044e08d630b0",
        "90": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%202.mp3?alt=media&token=7bb6d262-a52d-4db2-90eb-3d62a44061cf",
        "100": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%203.mp3?alt=media&token=202ec5d0-2ba6-4a97-9b20-7ea4670396e3",
        "110": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%204.mp3?alt=media&token=26959957-84dd-4e24-ac50-2b2e9903fcd2",
        "c80": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%201.mp3?alt=media&token=f5ab189d-51c1-4f6b-be29-044e08d630b0",
        "c90": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%202.mp3?alt=media&token=7bb6d262-a52d-4db2-90eb-3d62a44061cf",
        "c100": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%203.mp3?alt=media&token=202ec5d0-2ba6-4a97-9b20-7ea4670396e3",
        "c110": "https://firebasestorage.googleapis.com/v0/b/anda2-bda8a.appspot.com/o/sounds%2Fpalito%2FCLIP%204.mp3?alt=media&token=26959957-84dd-4e24-ac50-2b2e9903fcd2"
    }
}

### UPDATE STATUS OF A FRIEND
PATCH http://localhost:8383/changestatus
Content-Type: application/json

{
    "name": "tomato",
    "newStatus": "friend"
}


###DELETE A FRIEND
DELETE http://localhost:8383/friends
Content-Type: application/json

{
    "name": "banana"
}


